# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI
## Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    packages:
    - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

## We only support Ubuntu 14.04 and newer
dist: trusty

language: bash

git:
  ## EXPERIMENTAL
  ## Customizing the Build - Travis CI
  ## https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
  ## > Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.
  depth: 30
  ## We have recursive submodules, don't fetch it automatically
  submodules: false

cache:
- $HOME/Software

## The Build Lifecycle
## https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
before_install:
- git submodule init 'Continuous Integration/Utilities for Travis CI' 'Linters/GNU Bash Automatic Checking Program for Git Projects'
- git submodule update --depth=1

install:
- ./"Continuous Integration/Utilities for Travis CI/Setup ShellCheck's Latest Release without Re-building.bash"
- PATH="${HOME}/Software/shellcheck-stable:${PATH}"
- which -a shellcheck
- shellcheck --version

before_script:
- git lfs install # Install Git LFS config, which makes LFS files not making Git considered as "dirty"
- git lfs pull

script:
- ./'Linters/GNU Bash Automatic Checking Program for Git Projects/GNU Bash Automatic Checking Program for Git Projects.bash'
- ./setup-development-environment.bash
- ./build.bash

matrix:
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: tWizez4E4bVIXFZ80ZmdlA/pwezMJUf5wfPXNeZDE2rTffTJmAkCUb0t9ILf7h11IxuyRf8ElmRUx/jXay9UbY2SLI21QxwDLQkJefCKAG5rVwWOsGnmIHiyjbT96O5n24XSa53d6tkfKs0eL8wGtZ1R4P3rjTW5YTs5nc8kSTkEI5Hx0qr4y5nhbYOcRzyLhNRKsZIBBIZVpwF0IsneR1nMfnTA2XhlDyk1WQNcFsO8XVmPyaMv/4h/od68j1Lnq0bZBV6KbFJaWJguSAh89Xyz2FwEmPFlNZqYXBEHfr1aOLbfE54OUgFUmyZ8jpOutqPl5vKtGYxBlL2XvkvtUNxojFoPKy4HGEr87SUITTDh/RQDWTT8/jSMY5MsKQqjWYNy6f6cH7PPphLUXZblBTIG/h/jyQBndqfiiXaoIw/xmKYUF50fo6oQYwHBwp/XhnKhGfvZW5dmhDSjnrzbZ/RgnuNNp6iGphiWwdIRXplUjF2cGvSa1RvXNeusZ+HTAVCafqwK6CA5cVWQUm0dLqRZ7oby6F5TYKUcSY6nYKpow6eXphNIWgLd/vRKTqfTTFcc5hTv0H6C0cvVAHcExqypXy+mUWLqT2jRLSp4chvYd6hxSrZpQvJjNqyAtt21vskGrVCLOErrVJxFV9ppIVyMgBl2Wnaj1dhMxloGYbg=
  file_glob: true
  file: "Software Release/*.tar.bz2"
  skip_cleanup: true
  on:
    tags: true