# Travis CI Configuration
# https://docs.travis-ci.com
# This file is based on
# TravisCI · koalaman/shellcheck Wiki
# https://github.com/koalaman/shellcheck/wiki/TravisCI
## Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck
    - realpath      # Merged to GNU Coreutils in Ubuntu 16.04

## We only support Ubuntu 14.04 and newer
dist: trusty

language: bash

## EXPERIMENTAL
## Customizing the Build - Travis CI
## https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
## > Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.
git:
  depth: 1

install:
- ./Utilities\ for\ Travis\ CI/Install\ Git\ LFS\ in\ Travis\ CI\ Container\ Environment.bash
- PATH="${PWD}/$(printf git-lfs-*):${PATH}"

before_script:
- git lfs pull

script:
#- find . -name "*.bash" -print0 | xargs --max-args=1 shellcheck
# The following command will be dropped in favor with the above one after Travis CI environment contains ShellCheck >=0.4.5, which fixes the bug that triggers SC2148 even when `shell` directive is used
- find . -name "*.bash" -print0 | xargs --null --max-args=1 --verbose shellcheck --shell=bash
- ./build.bash

matrix:
  fast_finish: true

deploy:
  provider: releases
  api_key:
    secure: tWizez4E4bVIXFZ80ZmdlA/pwezMJUf5wfPXNeZDE2rTffTJmAkCUb0t9ILf7h11IxuyRf8ElmRUx/jXay9UbY2SLI21QxwDLQkJefCKAG5rVwWOsGnmIHiyjbT96O5n24XSa53d6tkfKs0eL8wGtZ1R4P3rjTW5YTs5nc8kSTkEI5Hx0qr4y5nhbYOcRzyLhNRKsZIBBIZVpwF0IsneR1nMfnTA2XhlDyk1WQNcFsO8XVmPyaMv/4h/od68j1Lnq0bZBV6KbFJaWJguSAh89Xyz2FwEmPFlNZqYXBEHfr1aOLbfE54OUgFUmyZ8jpOutqPl5vKtGYxBlL2XvkvtUNxojFoPKy4HGEr87SUITTDh/RQDWTT8/jSMY5MsKQqjWYNy6f6cH7PPphLUXZblBTIG/h/jyQBndqfiiXaoIw/xmKYUF50fo6oQYwHBwp/XhnKhGfvZW5dmhDSjnrzbZ/RgnuNNp6iGphiWwdIRXplUjF2cGvSa1RvXNeusZ+HTAVCafqwK6CA5cVWQUm0dLqRZ7oby6F5TYKUcSY6nYKpow6eXphNIWgLd/vRKTqfTTFcc5hTv0H6C0cvVAHcExqypXy+mUWLqT2jRLSp4chvYd6hxSrZpQvJjNqyAtt21vskGrVCLOErrVJxFV9ppIVyMgBl2Wnaj1dhMxloGYbg=
  file_glob: true
  file: "Software Release/*.tar.bz2"
  skip_cleanup: true
  on:
    repo: Lin-Buo-Ren/GNU-Bash-Shell-Script-Template
    tags: true