sudo: required
dist: trusty
# Fake language, we use Bash ;)
language: c
install:
  - sudo apt-add-repository multiverse
  - sudo apt-get update -qq
  - sudo apt-get install shellcheck
script:
- ./setup-development-environment.bash
- ./.git/hooks/pre-commit
#- ./build.bash
# No multiverse suite in container :(
#addons:
  #apt:
    #packages:
    #- shellcheck
